# Generated by Django 5.2.17 on 2026-08-12 02:47

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_kh', models.CharField(max_length=200, verbose_name='ឈ្មោះការិយាល័យ/អង្គភាព (ខ្មែរ)')),
                ('name_en', models.CharField(blank=True, max_length=200, verbose_name='English Name')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='កូដលិខិត/លេខកូដ (Dept Code)')),
                ('description', models.TextField(blank=True, verbose_name='ការពណ៌នា')),
            ],
            options={
                'verbose_name': 'ការិយាល័យ/អង្គភាព',
                'verbose_name_plural': 'បញ្ជីការិយាល័យ/អង្គភាព',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('INBOUND', 'លិខិតចូល (Inbound)'), ('OUTBOUND', 'លិខិតចេញ (Outbound)'), ('INTERNAL', 'លិខិតផ្ទៃក្នុង (Internal)')], default='INBOUND', max_length=20, verbose_name='ប្រភេទលិខិត')),
                ('registry_number', models.CharField(max_length=100, unique=True, verbose_name='លេខចុះលិខិត (Registry Code)')),
                ('title', models.CharField(max_length=500, verbose_name='កម្មវត្ថុ (ចំណងជើងលិខិត)')),
                ('summary', models.TextField(blank=True, verbose_name='សង្ខេបខ្លឹមសារ/បរិយាយ')),
                ('origin_org', models.CharField(max_length=250, verbose_name='ប្រភពលិខិត/ផ្ញើមកពីណា')),
                ('destination_org', models.CharField(max_length=250, verbose_name='អ្នកទទួល/ផ្ញើទៅណា')),
                ('urgency', models.CharField(choices=[('NORMAL', 'ធម្មតា (Normal)'), ('URGENT', 'ប្រញាប់ (Urgent)'), ('MOST_URGENT', 'ប្រញាប់បំផុត (Most Urgent)')], default='NORMAL', max_length=20, verbose_name='កម្រិតប្រញាប់')),
                ('secrecy', models.CharField(choices=[('NORMAL', 'ធម្មតា'), ('CONFIDENTIAL', 'សម្ងាត់'), ('MOST_CONFIDENTIAL', 'សម្ងាត់បំផុត')], default='NORMAL', max_length=20, verbose_name='កម្រិតសម្ងាត់')),
                ('status', models.CharField(choices=[('DRAFT', 'ព្រាងឯកសារ (Draft)'), ('PENDING_ADMIN', 'រង់ចាំរដ្ឋបាលពិនិត្យ (Pending Admin)'), ('PENDING_LEADERSHIP', 'រង់ចាំថ្នាក់ដឹកនាំពិនិត្យ/ធ្វើចំណារ (Pending Leadership)'), ('ANNOTATED', 'បានធ្វើចំណាររួច (Annotated)'), ('ROUTED', 'បានបញ្ជូនទៅការិយាល័យជំនាញ (Routed)'), ('IN_PROGRESS', 'កំពុងចាត់ចែង (In Progress)'), ('COMPLETED', 'បានចាត់ចែងរួចរាល់ (Completed)'), ('REJECTED', 'បដិសេធ/បញ្ជូនត្រឡប់ (Rejected)')], default='DRAFT', max_length=25, verbose_name='ស្ថានភាពលំហូរ')),
                ('issue_date', models.DateField(default=django.utils.timezone.now, verbose_name='ថ្ងៃខែឆ្នាំលើលិខិត')),
                ('received_date', models.DateField(default=django.utils.timezone.now, verbose_name='ថ្ងៃខែឆ្នាំ ចុះចូលប្រព័ន្ធ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_documents', to=settings.AUTH_USER_MODEL, verbose_name='អ្នកទទួលបន្ទុកចាត់ចែង')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_documents', to=settings.AUTH_USER_MODEL, verbose_name='អ្នកបង្កើត')),
                ('current_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_documents', to='dms.department', verbose_name='កំពុងស្ថិតនៅការិយាល័យ')),
                ('origin_department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='originating_documents', to='dms.department', verbose_name='ការិយាល័យដើម')),
            ],
            options={
                'verbose_name': 'ឯកសារ',
                'verbose_name_plural': 'បញ្ជីឯកសារ',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentRouting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_taken', models.CharField(max_length=250, verbose_name='សកម្មភាពបញ្ជូន')),
                ('notes', models.TextField(blank=True, verbose_name='ចំណាំ/កត់សម្គាល់')),
                ('routed_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routings', to='dms.document', verbose_name='ឯកសារ')),
                ('from_dept', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_dept_routings', to='dms.department', verbose_name='ពីការិយាល័យ')),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_routings', to=settings.AUTH_USER_MODEL, verbose_name='អ្នកបញ្ជូន')),
                ('to_dept', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_dept_routings', to='dms.department', verbose_name='ទៅកាន់ការិយាល័យ')),
                ('to_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_routings', to=settings.AUTH_USER_MODEL, verbose_name='ទៅកាន់អ្នកទទួល')),
            ],
            options={
                'verbose_name': 'ប្រវត្តិបញ្ជូនឯកសារ',
                'verbose_name_plural': 'ប្រវត្តិបញ្ជូនឯកសារ',
                'ordering': ['-routed_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.CharField(default='1.0', max_length=20, verbose_name='ជំនាន់ (Version)')),
                ('file', models.FileField(upload_to='documents/%Y/%m/', verbose_name='ឯកសារភ្ជាប់ (PDF/Image)')),
                ('file_name', models.CharField(blank=True, max_length=255, verbose_name='ឈ្មោះស្រាប់')),
                ('change_summary', models.TextField(blank=True, verbose_name='ចំណាំនៃការកែប្រែ')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='dms.document', verbose_name='ឯកសារ')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='អ្នក Upload')),
            ],
            options={
                'verbose_name': 'ជំនាន់ឯកសារ',
                'verbose_name_plural': 'បញ្ជីជំនាន់ឯកសារ',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='LeadershipAnnotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(choices=[('APPROVED', 'ឯកភាព (Approved)'), ('ACTION_REQUIRED', 'សូមចាត់ចែង (Please Action)'), ('REVIEW', 'សូមពិនិត្យ និងផ្តល់យោបល់ (Please Review)'), ('REJECTED', 'បដិសេធ (Rejected)'), ('CUSTOM', 'ចំណារផ្សេងៗ (Custom Note)')], default='ACTION_REQUIRED', max_length=30, verbose_name='ការសម្រេច/ប្រភេទចំណារ')),
                ('annotation_text', models.TextField(verbose_name='ខ្លឹមសារចំណារ')),
                ('signed_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='កាលបរិច្ឆេទធ្វើចំណារ')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to='dms.document', verbose_name='ឯកសារ')),
                ('leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ថ្នាក់ដឹកនាំធ្វើចំណារ')),
                ('target_departments', models.ManyToManyField(related_name='received_annotations', to='dms.department', verbose_name='ចាត់ចែងជូនការិយាល័យ')),
            ],
            options={
                'verbose_name': 'ចំណារថ្នាក់ដឹកនាំ',
                'verbose_name_plural': 'បញ្ជីចំណារថ្នាក់ដឹកនាំ',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='ចំណងជើងជូនដំណឹង')),
                ('message', models.TextField(verbose_name='សារ')),
                ('is_read', models.BooleanField(default=False, verbose_name='បានអានរួច')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dms.document', verbose_name='ឯកសារពាក់ព័ន្ធ')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='អ្នកទទួល')),
            ],
            options={
                'verbose_name': 'សារជូនដំណឹង',
                'verbose_name_plural': 'បញ្ជីសារជូនដំណឹង',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('LEADERSHIP', 'ថ្នាក់ដឹកនាំ (Leadership)'), ('ADMIN', 'ការិយាល័យរដ្ឋបាល (Admin Office)'), ('SPECIALIZED', 'ការិយាល័យជំនាញ (Specialized Office)')], default='SPECIALIZED', max_length=20, verbose_name='តួនាទីសិទ្ធិ')),
                ('position_title', models.CharField(blank=True, max_length=150, verbose_name='មុខតំណែង')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='លេខទូរស័ព្ទ')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='dms.department', verbose_name='ការិយាល័យ/អង្គភាព')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ព័ត៌មានអ្នកប្រើប្រាស់',
                'verbose_name_plural': 'បញ្ជីព័ត៌មានអ្នកប្រើប្រាស់',
            },
        ),
    ]
