# Generated by Django 5.2.17 on 2026-08-17 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTPVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=150, verbose_name='Email ឬ លេខទូរស័ព្ទ')),
                ('otp_code', models.CharField(max_length=6, verbose_name='លេខកូដ ៦ខ្ទង់')),
                ('purpose', models.CharField(choices=[('REGISTER', 'ចុះឈ្មោះថ្មី (Registration)'), ('LOGIN', 'ចូលប្រព័ន្ធ (Login)'), ('RESET_PASSWORD', 'ផ្លាស់ប្តូរពាក្យសម្ងាត់ (Reset Password)')], default='REGISTER', max_length=20, verbose_name='គោលបំណង')),
                ('payload_data', models.JSONField(blank=True, null=True, verbose_name='ទិន្នន័យបណ្តោះអាសន្ន')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(verbose_name='ផុតកំណត់នៅពេល')),
                ('is_used', models.BooleanField(default=False, verbose_name='បានប្រើប្រាស់រួច')),
            ],
            options={
                'verbose_name': 'ការផ្ទៀងផ្ទាត់ OTP',
                'verbose_name_plural': 'បញ្ជីផ្ទៀងផ្ទាត់ OTP',
                'ordering': ['-created_at'],
            },
        ),
    ]
