# Generated by Django 5.2.17 on 2026-08-17 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dms', '0002_otpverification'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='បានអនុម័តដោយ Admin'),
        ),
    ]
