# Generated by Django 5.2.17 on 2026-08-17 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dms', '0004_populate_official_departments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='position_title',
            field=models.CharField(blank=True, choices=[('ប្រធានមន្ទីរ', 'ប្រធានមន្ទីរ'), ('អនុប្រធានមន្ទីរ', 'អនុប្រធានមន្ទីរ'), ('ប្រធានការិយាល័យ', 'ប្រធានការិយាល័យ'), ('អនុប្រធានការិយាល័យ', 'អនុប្រធានការិយាល័យ'), ('មន្ត្រី', 'មន្ត្រី')], default='មន្ត្រី', max_length=150, verbose_name='មុខតំណែង'),
        ),
    ]
