# Generated by Django 5.2.17 on 2026-08-17 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dms', '0005_alter_userprofile_position_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='raw_password_display',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ពាក្យសម្ងាត់ (សម្រាប់ Admin ពិនិត្យ)'),
        ),
    ]
