# Generated by Django 5.2.17 on 2026-08-17 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dms', '0006_userprofile_raw_password_display'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='can_annotate',
            field=models.BooleanField(default=False, verbose_name='សិទ្ធិផ្តល់ចំណារថ្នាក់ដឹកនាំ (Leadership Annotation)'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_complete_document',
            field=models.BooleanField(default=False, verbose_name='សិទ្ធិបញ្ចប់លិខិត (Complete Doc)'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_create_document',
            field=models.BooleanField(default=True, verbose_name='សិទ្ធិចុះបញ្ជីលិខិត (Create Doc)'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_delete_document',
            field=models.BooleanField(default=False, verbose_name='សិទ្ធិលុបលិខិត (Delete Doc)'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_edit_document',
            field=models.BooleanField(default=True, verbose_name='សិទ្ធិកែប្រែ/បន្ថែម Version ឯកសារ'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_print',
            field=models.BooleanField(default=True, verbose_name='សិទ្ធិបោះពុម្ពប័ណ្ណតាមដាន (Print)'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_route_document',
            field=models.BooleanField(default=True, verbose_name='សិទ្ធិបញ្ជូន/ចាត់ចែងលិខិត (Route Doc)'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_view_reports',
            field=models.BooleanField(default=True, verbose_name='សិទ្ធិមើលរបាយការណ៍ & Export Excel'),
        ),
    ]
