# Generated by Django 5.2.17 on 2026-08-17 02:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dms', '0007_userprofile_can_annotate_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='documentrouting',
            name='is_broadcast',
            field=models.BooleanField(default=False, verbose_name='បញ្ជូនទៅគ្រប់ការិយាល័យទាំងអស់ (Broadcast)'),
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='ខ្លឹមសារសារ')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='chat_attachments/', verbose_name='ឯកសារភ្ជាប់')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_messages', to='dms.department', verbose_name='ការិយាល័យអ្នកផ្ញើ')),
                ('related_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_chats', to='dms.document', verbose_name='លិខិតពាក់ព័ន្ធ')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL, verbose_name='អ្នកផ្ញើ')),
                ('target_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_chats', to='dms.department', verbose_name='ការិយាល័យគោលដៅ (ទុកទំនេរបើសាធារណៈ)')),
            ],
            options={
                'verbose_name': 'សារជជែក (Live Chat)',
                'verbose_name_plural': 'សារជជែកទាំងអស់ (Live Chat)',
                'ordering': ['created_at'],
            },
        ),
    ]
