# Generated by Django 5.2.17 on 2026-08-17 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dms', '0008_documentrouting_is_broadcast_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='is_edited',
            field=models.BooleanField(default=False, verbose_name='បានកែប្រែ'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
