# Generated by Django 5.2.17 on 2026-08-17 03:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dms', '0009_chatmessage_is_edited_chatmessage_updated_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='documentrouting',
            name='cancellation_reason',
            field=models.TextField(blank=True, verbose_name='មូលហេតុលុបចោល'),
        ),
        migrations.AddField(
            model_name='documentrouting',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='កាលបរិច្ឆេទលុបចោល'),
        ),
        migrations.AddField(
            model_name='documentrouting',
            name='cancelled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_routings', to=settings.AUTH_USER_MODEL, verbose_name='អ្នកលុបចោល'),
        ),
        migrations.AddField(
            model_name='documentrouting',
            name='is_cancelled',
            field=models.BooleanField(default=False, verbose_name='បានលុបចោលការបញ្ជូន (Cancelled)'),
        ),
        migrations.AlterField(
            model_name='document',
            name='destination_org',
            field=models.CharField(blank=True, default='', max_length=250, verbose_name='អ្នកទទួល/ផ្ញើទៅណា'),
        ),
        migrations.AlterField(
            model_name='document',
            name='origin_org',
            field=models.CharField(blank=True, default='', max_length=250, verbose_name='ប្រភពលិខិត/ផ្ញើមកពីណា'),
        ),
    ]
