# Generated by Django 5.2.17 on 2026-08-17 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dms', '0010_documentrouting_cancellation_reason_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='doc_type',
            field=models.CharField(choices=[('INBOUND', 'លិខិតចូល (Inbound)'), ('OUTBOUND', 'លិខិតចេញ (Outbound)')], default='OUTBOUND', max_length=20, verbose_name='ប្រភេទលិខិត'),
        ),
    ]
