# Generated by Django 5.2.17 on 2026-08-17 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dms', '0011_alter_document_doc_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='doc_type',
            field=models.CharField(choices=[('INBOUND', 'លិខិតចូល (Inbound)'), ('OUTBOUND', 'លិខិតចេញ (Outbound)'), ('INTERNAL', 'លិខិតផ្ទៃក្នុង (Internal)')], default='OUTBOUND', max_length=20, verbose_name='ប្រភេទលិខិត'),
        ),
    ]
