# Generated by Django 6.1 on 2026-08-17 10:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dms', '0013_civilservantprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OfficerAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('PERSONAL', 'ក- ឯកសារអត្តសញ្ញាណ និងផ្ទាល់ខ្លួន (ID/Birth/Family Book)'), ('FAMILY', 'ខ- សំបុត្រអាពាហ៍ពិពាហ៍ និងគ្រួសារ (Marriage/Children)'), ('EDUCATION', 'ឃ- សញ្ញាបត្រ និងវិញ្ញាបនបត្របណ្តុះបណ្តាល (Degrees/Certificates)'), ('APPOINTMENT', 'ច- ព្រះរាជក្រឹត្យ អនុក្រឹត្យ និងប្រកាសតាំងស៊ប់/តែងតាំង (Decrees/Prakas)'), ('PROMOTION', 'ឆ- លិខិតដំឡើងឋានន្តរស័ក្តិ និងថ្នាក់ (Promotions)'), ('AWARD', 'ជ- ព្រះរាជក្រឹត្យគ្រឿងឥស្សរិយយស មេដាយ និងប័ណ្ណសរសើរ (Awards/Medals)'), ('OTHER', 'ឯកសារយោងផ្សេងៗ (Other Reference Documents)')], default='OTHER', max_length=50, verbose_name='ប្រភេទឯកសារយោង')),
                ('title', models.CharField(max_length=255, verbose_name='ចំណងជើង/ឈ្មោះឯកសារ')),
                ('doc_number', models.CharField(blank=True, max_length=150, verbose_name='លេខលិខិត/ឯកសារ')),
                ('issued_date', models.CharField(blank=True, max_length=100, verbose_name='កាលបរិច្ឆេទចេញលិខិត')),
                ('file', models.FileField(upload_to='officer_attachments/%Y/%m/', verbose_name='ឯកសារភ្ជាប់')),
                ('file_size', models.PositiveIntegerField(default=0, verbose_name='ទំហំឯកសារ (Bytes)')),
                ('description', models.TextField(blank=True, verbose_name='ការពិពណ៌នា/កំណត់ចំណាំ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('officer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='dms.civilservantprofile', verbose_name='មន្ត្រីរាជការ')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='អ្នកបញ្ចូល')),
            ],
            options={
                'verbose_name': 'ឯកសារយោងមន្ត្រីរាជការ',
                'verbose_name_plural': 'ឯកសារយោងមន្ត្រីរាជការ',
                'ordering': ['category', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OfficerAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('UPLOAD', 'បញ្ចូលឯកសារយោងថ្មី'), ('VIEW', 'មើល/ទាញយកឯកសារយោង'), ('EDIT', 'កែប្រែ/ប្តូរឯកសារយោង'), ('DELETE', 'លុបឯកសារយោង'), ('PROFILE_CREATE', 'បញ្ចូលជីវប្រវត្តិមន្ត្រីថ្មី'), ('PROFILE_EDIT', 'កែប្រែជីវប្រវត្តិមន្ត្រី'), ('PROFILE_DELETE', 'លុបជីវប្រវត្តិមន្ត្រី')], max_length=50, verbose_name='ប្រភេទសកម្មភាព')),
                ('attachment_title', models.CharField(blank=True, max_length=255, verbose_name='ឈ្មោះឯកសារ')),
                ('category', models.CharField(blank=True, max_length=100, verbose_name='ផ្នែក/មុខងារ')),
                ('details', models.TextField(blank=True, verbose_name='ព័ត៌មានលម្អិត')),
                ('ip_address', models.CharField(blank=True, max_length=50, verbose_name='IP Address')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='កាលបរិច្ឆេទ-ម៉ោង')),
                ('officer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='dms.civilservantprofile', verbose_name='មន្ត្រីរាជការ')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='អ្នកធ្វើសកម្មភាព')),
            ],
            options={
                'verbose_name': 'កំណត់ត្រាសកម្មភាពមន្ត្រី',
                'verbose_name_plural': 'កំណត់ត្រាសកម្មភាពមន្ត្រី (Audit Logs)',
                'ordering': ['-timestamp'],
            },
        ),
    ]
