# Generated by Django 6.1 on 2026-08-17 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dms', '0014_officerattachment_officerauditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='civilservantprofile',
            name='position_code',
            field=models.CharField(blank=True, max_length=50, verbose_name='កូដមុខតំណែង / Code ID'),
        ),
    ]
