# Generated by Django 6.1 on 2026-08-17 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dms', '0015_civilservantprofile_position_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='officerauditlog',
            name='officer_name_cache',
            field=models.CharField(blank=True, max_length=200, verbose_name='ឈ្មោះមន្ត្រី (Snapshot)'),
        ),
        migrations.AlterField(
            model_name='officerauditlog',
            name='officer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='dms.civilservantprofile', verbose_name='មន្ត្រីរាជការ'),
        ),
    ]
