# Generated by Django 5.2.17 on 2026-08-19 01:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dms', '0016_officerauditlog_officer_name_cache_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='officerauditlog',
            name='action_type',
            field=models.CharField(choices=[('UPLOAD', 'បញ្ចូលឯកសារយោងថ្មី'), ('VIEW', 'មើល/ទាញយកឯកសារយោង'), ('EDIT', 'កែប្រែ/ប្តូរឯកសារយោង'), ('DELETE', 'លុបឯកសារយោង'), ('PROFILE_CREATE', 'បញ្ចូលជីវប្រវត្តិមន្ត្រីថ្មី'), ('PROFILE_EDIT', 'កែប្រែជីវប្រវត្តិមន្ត្រី'), ('PROFILE_DELETE', 'លុបជីវប្រវត្តិមន្ត្រី'), ('PROFILE_BULK_DELETE', 'លុបជីវប្រវត្តិមន្ត្រីជាក្រុម/ទាំងអស់'), ('SETTING_UPDATE', 'កែប្រែកាលវិភាគ/ការកំណត់')], max_length=50, verbose_name='ប្រភេទសកម្មភាព'),
        ),
        migrations.CreateModel(
            name='OfficerEditWindowSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='បើកដំណើរការកាលវិភាគ (Enable Window)')),
                ('start_datetime', models.DateTimeField(blank=True, null=True, verbose_name='កាលបរិច្ឆេទ & ម៉ោង ចាប់ផ្តើម')),
                ('end_datetime', models.DateTimeField(blank=True, null=True, verbose_name='កាលបរិច្ឆេទ & ម៉ោង បញ្ចប់ (Deadline)')),
                ('title', models.CharField(default='កាលវិភាគកែប្រែ និងបញ្ចូលជីវប្រវត្តិមន្ត្រី', max_length=255, verbose_name='ចំណងជើងកាលវិភាគ')),
                ('instruction_note', models.TextField(blank=True, default='សូមគ្រប់ការិយាល័យជំនាញទាំងអស់ មេត្តារួសរាន់បញ្ចូល និងកែសម្រួលព័ត៌មានជីវប្រវត្តិមន្ត្រីឱ្យបានទាន់ពេលវេលាកំណត់។', verbose_name='សេចក្តីណែនាំ/សារជូនដំណឹង')),
                ('allow_specialized_edit', models.BooleanField(default=True, verbose_name='អនុញ្ញាតឱ្យការិយាល័យជំនាញកែប្រែ/បញ្ចូល')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='កាលបរិច្ឆេទកែប្រែចុងក្រោយ')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='កែប្រែចុងក្រោយដោយ')),
            ],
            options={
                'verbose_name': 'ការកំណត់កាលវិភាគកែប្រែជីវប្រវត្តិ',
                'verbose_name_plural': 'ការកំណត់កាលវិភាគកែប្រែជីវប្រវត្តិ',
            },
        ),
    ]
