# Generated by Django 5.2.17 on 2026-08-19 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dms', '0017_alter_officerauditlog_action_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='officereditwindowsetting',
            name='allowed_departments',
            field=models.ManyToManyField(blank=True, related_name='edit_window_settings', to='dms.department', verbose_name='ការិយាល័យដែលអនុញ្ញាត (ទុកទទេ = គ្រប់ការិយាល័យទាំងអស់)'),
        ),
    ]
