# Generated by Django 5.2.17 on 2026-08-19 02:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dms', '0018_officereditwindowsetting_allowed_departments'),
    ]

    operations = [
        migrations.CreateModel(
            name='CambodiaProvince',
            fields=[
                ('code', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='កូដរាជធានី/ខេត្ត')),
                ('name_kh', models.CharField(db_index=True, max_length=150, verbose_name='ឈ្មោះរាជធានី/ខេត្ត (ខ្មែរ)')),
                ('name_en', models.CharField(blank=True, max_length=150, verbose_name='ឈ្មោះរាជធានី/ខេត្ត (ឡាតាំង)')),
            ],
            options={
                'verbose_name': 'រាជធានី/ខេត្ត',
                'verbose_name_plural': 'បញ្ជីរាជធានី/ខេត្ត',
                'ordering': ['code'],
            },
        ),
        migrations.AddField(
            model_name='civilservantprofile',
            name='current_commune_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='កូដឃុំ/សង្កាត់បច្ចុប្បន្ន'),
        ),
        migrations.AddField(
            model_name='civilservantprofile',
            name='current_district_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='កូដស្រុក/ខណ្ឌបច្ចុប្បន្ន'),
        ),
        migrations.AddField(
            model_name='civilservantprofile',
            name='current_province_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='កូដរាជធានី/ខេត្តបច្ចុប្បន្ន'),
        ),
        migrations.AddField(
            model_name='civilservantprofile',
            name='current_village_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='កូដភូមិបច្ចុប្បន្ន'),
        ),
        migrations.AddField(
            model_name='civilservantprofile',
            name='perm_commune_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='កូដឃុំ/សង្កាត់អចិន្ត្រៃយ៍'),
        ),
        migrations.AddField(
            model_name='civilservantprofile',
            name='perm_district_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='កូដស្រុក/ខណ្ឌអចិន្ត្រៃយ៍'),
        ),
        migrations.AddField(
            model_name='civilservantprofile',
            name='perm_province_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='កូដរាជធានី/ខេត្តអចិន្ត្រៃយ៍'),
        ),
        migrations.AddField(
            model_name='civilservantprofile',
            name='perm_village_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='កូដភូមិអចិន្ត្រៃយ៍'),
        ),
        migrations.AddField(
            model_name='civilservantprofile',
            name='pob_commune_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='កូដឃុំ/សង្កាត់កំណើត'),
        ),
        migrations.AddField(
            model_name='civilservantprofile',
            name='pob_district_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='កូដស្រុក/ខណ្ឌកំណើត'),
        ),
        migrations.AddField(
            model_name='civilservantprofile',
            name='pob_province_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='កូដរាជធានី/ខេត្តកំណើត'),
        ),
        migrations.AddField(
            model_name='civilservantprofile',
            name='pob_village_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='កូដភូមិកំណើត'),
        ),
        migrations.CreateModel(
            name='CambodiaDistrict',
            fields=[
                ('code', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='កូដក្រុង/ស្រុក/ខណ្ឌ')),
                ('name_kh', models.CharField(db_index=True, max_length=150, verbose_name='ឈ្មោះក្រុង/ស្រុក/ខណ្ឌ (ខ្មែរ)')),
                ('name_en', models.CharField(blank=True, max_length=150, verbose_name='ឈ្មោះក្រុង/ស្រុក/ខណ្ឌ (ឡាតាំង)')),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='dms.cambodiaprovince', verbose_name='រាជធានី/ខេត្ត')),
            ],
            options={
                'verbose_name': 'ក្រុង/ស្រុក/ខណ្ឌ',
                'verbose_name_plural': 'បញ្ជីក្រុង/ស្រុក/ខណ្ឌ',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='CambodiaCommune',
            fields=[
                ('code', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='កូដឃុំ/សង្កាត់')),
                ('name_kh', models.CharField(db_index=True, max_length=150, verbose_name='ឈ្មោះឃុំ/សង្កាត់ (ខ្មែរ)')),
                ('name_en', models.CharField(blank=True, max_length=150, verbose_name='ឈ្មោះឃុំ/សង្កាត់ (ឡាតាំង)')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communes', to='dms.cambodiadistrict', verbose_name='ក្រុង/ស្រុក/ខណ្ឌ')),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communes', to='dms.cambodiaprovince', verbose_name='រាជធានី/ខេត្ត')),
            ],
            options={
                'verbose_name': 'ឃុំ/សង្កាត់',
                'verbose_name_plural': 'បញ្ជីឃុំ/សង្កាត់',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='CambodiaVillage',
            fields=[
                ('code', models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='កូដភូមិ')),
                ('name_kh', models.CharField(db_index=True, max_length=150, verbose_name='ឈ្មោះភូមិ (ខ្មែរ)')),
                ('name_en', models.CharField(blank=True, max_length=150, verbose_name='ឈ្មោះភូមិ (ឡាតាំង)')),
                ('commune', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='villages', to='dms.cambodiacommune', verbose_name='ឃុំ/សង្កាត់')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='villages', to='dms.cambodiadistrict', verbose_name='ក្រុង/ស្រុក/ខណ្ឌ')),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='villages', to='dms.cambodiaprovince', verbose_name='រាជធានី/ខេត្ត')),
            ],
            options={
                'verbose_name': 'ភូមិ',
                'verbose_name_plural': 'បញ្ជីភូមិ',
                'ordering': ['code', 'name_kh'],
            },
        ),
    ]
