# Generated by Django 5.2.17 on 2026-08-19 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dms', '0019_cambodiaprovince_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cambodiavillage',
            options={'ordering': ['code', 'name_kh'], 'verbose_name': 'ភូមិ', 'verbose_name_plural': 'បញ្ជីភូមិ'},
        ),
        migrations.AddField(
            model_name='cambodiavillage',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='cambodiavillage',
            name='code',
            field=models.CharField(db_index=True, max_length=30, verbose_name='កូដភូមិ'),
        ),
    ]
