# Generated by Django 5.2.17 on 2026-08-19 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dms', '0019_cambodiaprovince_and_more'),
    ]

    operations = [
    ]
