# Generated by Django 5.2.17 on 2026-08-20 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dms', '0020_alter_cambodiavillage_options_cambodiavillage_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['order_index', 'name_kh'], 'verbose_name': 'ការិយាល័យ/អង្គភាព', 'verbose_name_plural': 'បញ្ជីការិយាល័យ/អង្គភាព'},
        ),
        migrations.AddField(
            model_name='department',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='ស្ថានភាពដំណើរការ'),
        ),
        migrations.AddField(
            model_name='department',
            name='order_index',
            field=models.IntegerField(default=100, verbose_name='លំដាប់លំដោយ'),
        ),
        migrations.AddField(
            model_name='department',
            name='structure_type',
            field=models.CharField(choices=[('OLD', 'រចនាសម្ព័ន្ធចាស់ (ការិយាល័យទាំង១០ + ខណ្ឌទាំង២)'), ('NEW', 'រចនាសម្ព័ន្ធថ្មី'), ('CORE', 'ថ្នាក់ដឹកនាំ/រចនាសម្ព័ន្ធស្នូល')], default='OLD', max_length=20, verbose_name='ប្រភេទរចនាសម្ព័ន្ធ'),
        ),
        migrations.AlterField(
            model_name='department',
            name='code',
            field=models.CharField(max_length=50, unique=True, verbose_name='កូដលិខិត/លេខកូដ (Dept Code)'),
        ),
    ]
