# Generated by Django 6.1 on 2026-08-20 16:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dms', '0022_setup_old_and_new_departments'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OfficerMedalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_year', models.IntegerField(default=2026, verbose_name='សម្រាប់ឆ្នាំ')),
                ('proposed_medal', models.CharField(max_length=200, verbose_name='មេដាយ/គ្រឿងឥស្សរិយយសដែលស្នើសុំ')),
                ('years_of_service', models.CharField(blank=True, max_length=100, verbose_name='អតីតភាពការងារសរុប (ឆ្នាំ)')),
                ('achievements', models.TextField(blank=True, verbose_name='ស្នាដៃ និងគុណសម្បត្តិការងារ')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='medals/requests/%Y/', verbose_name='ឯកសារយោងភ្ជាប់')),
                ('status', models.CharField(choices=[('PENDING', 'កំពុងរង់ចាំពិនិត្យ (Pending)'), ('APPROVED', 'បានអនុម័ត/ឯកភាព (Approved)'), ('REJECTED', 'មិនទាន់ឯកភាព (Rejected)')], default='PENDING', max_length=20, verbose_name='ស្ថានភាពពិនិត្យ')),
                ('admin_notes', models.TextField(blank=True, verbose_name='មតិយោបល់/កំណត់សម្គាល់របស់ Admin')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='កាលបរិច្ឆេទពិនិត្យ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='កាលបរិច្ឆេទស្នើសុំ')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medal_requests', to='dms.department', verbose_name='ការិយាល័យស្នើសុំ')),
                ('officer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medal_requests', to='dms.civilservantprofile', verbose_name='មន្ត្រីស្នើសុំ')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_medal_requests', to=settings.AUTH_USER_MODEL, verbose_name='អ្នកពិនិត្យ/អនុម័ត')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_medal_requests', to=settings.AUTH_USER_MODEL, verbose_name='អ្នកស្នើសុំ')),
            ],
            options={
                'verbose_name': 'សំណើសុំមេដាយ',
                'verbose_name_plural': 'បញ្ជីសំណើសុំមេដាយ',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OfficerPromotionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_year', models.IntegerField(default=2026, verbose_name='សម្រាប់ឆ្នាំ')),
                ('promotion_type', models.CharField(choices=[('SENIORITY', 'តាមវេនជ្រើសរើស / អតីតភាពការងារ (២ ឆ្នាំ)'), ('DEGREE', 'តាមកម្រិតសញ្ញាបត្រ'), ('EXAM', 'តាមការប្រឡងប្រជែង'), ('SPECIAL', 'ករណីពិសេស / គុណសម្បត្តិការងារ')], default='SENIORITY', max_length=50, verbose_name='ប្រភេទនៃការដំឡើង')),
                ('current_rank_and_step', models.CharField(blank=True, max_length=150, verbose_name='ក្របខ័ណ្ឌ និងថ្នាក់បច្ចុប្បន្ន')),
                ('proposed_rank_and_step', models.CharField(max_length=150, verbose_name='ថ្នាក់ដែលស្នើសុំដំឡើងទៅ')),
                ('years_in_current_rank', models.CharField(blank=True, max_length=100, verbose_name='អតីតភាពក្នុងថ្នាក់')),
                ('reason', models.TextField(blank=True, verbose_name='មូលហេតុ និងសមិទ្ធផលការងារ')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='promotions/requests/%Y/', verbose_name='ឯកសារយោងភ្ជាប់')),
                ('status', models.CharField(choices=[('PENDING', 'កំពុងរង់ចាំពិនិត្យ (Pending)'), ('APPROVED', 'បានអនុម័ត/ឯកភាព (Approved)'), ('REJECTED', 'មិនទាន់ឯកភាព (Rejected)')], default='PENDING', max_length=20, verbose_name='ស្ថានភាពពិនិត្យ')),
                ('admin_notes', models.TextField(blank=True, verbose_name='មតិយោបល់/កំណត់សម្គាល់របស់ Admin')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='កាលបរិច្ឆេទពិនិត្យ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='កាលបរិច្ឆេទស្នើសុំ')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promotion_requests', to='dms.department', verbose_name='ការិយាល័យស្នើសុំ')),
                ('officer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotion_requests', to='dms.civilservantprofile', verbose_name='មន្ត្រីស្នើសុំ')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_promotion_requests', to=settings.AUTH_USER_MODEL, verbose_name='អ្នកពិនិត្យ/អនុម័ត')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_promotion_requests', to=settings.AUTH_USER_MODEL, verbose_name='អ្នកស្នើសុំ')),
            ],
            options={
                'verbose_name': 'សំណើសុំដំឡើងថ្នាក់',
                'verbose_name_plural': 'បញ្ជីសំណើសុំដំឡើងថ្នាក់',
                'ordering': ['-created_at'],
            },
        ),
    ]
