# Generated by Django 6.1 on 2026-08-20 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dms', '0023_officermedalrequest_officerpromotionrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='officermedalrequest',
            name='is_submitted_to_ministry',
            field=models.BooleanField(default=False, verbose_name='បានបញ្ជូនទៅក្រសួងរួច'),
        ),
        migrations.AddField(
            model_name='officermedalrequest',
            name='meeting_decision',
            field=models.TextField(blank=True, verbose_name='មតិអង្គប្រជុំ/គណៈកម្មការវាយតម្លៃ'),
        ),
        migrations.AddField(
            model_name='officermedalrequest',
            name='ministry_doc_number',
            field=models.CharField(blank=True, max_length=150, verbose_name='លេខលិខិតបញ្ជូនទៅក្រសួង'),
        ),
        migrations.AddField(
            model_name='officermedalrequest',
            name='ministry_submission_date',
            field=models.DateField(blank=True, null=True, verbose_name='កាលបរិច្ឆេទបញ្ជូនទៅក្រសួង'),
        ),
        migrations.AddField(
            model_name='officerpromotionrequest',
            name='is_submitted_to_ministry',
            field=models.BooleanField(default=False, verbose_name='បានបញ្ជូនទៅក្រសួងរួច'),
        ),
        migrations.AddField(
            model_name='officerpromotionrequest',
            name='meeting_decision',
            field=models.TextField(blank=True, verbose_name='មតិអង្គប្រជុំ/គណៈកម្មការវាយតម្លៃ'),
        ),
        migrations.AddField(
            model_name='officerpromotionrequest',
            name='ministry_doc_number',
            field=models.CharField(blank=True, max_length=150, verbose_name='លេខលិខិតបញ្ជូនទៅក្រសួង'),
        ),
        migrations.AddField(
            model_name='officerpromotionrequest',
            name='ministry_submission_date',
            field=models.DateField(blank=True, null=True, verbose_name='កាលបរិច្ឆេទបញ្ជូនទៅក្រសួង'),
        ),
    ]
