# Generated by Django 6.1 on 2026-08-20 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dms', '0024_officermedalrequest_is_submitted_to_ministry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='officermedalrequest',
            name='effective_date',
            field=models.DateField(blank=True, null=True, verbose_name='កាលបរិច្ឆេទចូលជាធរមាន'),
        ),
        migrations.AddField(
            model_name='officermedalrequest',
            name='is_profile_updated',
            field=models.BooleanField(default=False, verbose_name='បាន Update Profile រួច'),
        ),
        migrations.AddField(
            model_name='officermedalrequest',
            name='legal_doc_date',
            field=models.DateField(blank=True, null=True, verbose_name='កាលបរិច្ឆេទចុះហត្ថលេខា'),
        ),
        migrations.AddField(
            model_name='officermedalrequest',
            name='legal_doc_number',
            field=models.CharField(blank=True, max_length=150, verbose_name='លេខប្រកាស/អនុក្រឹត្យ/ព្រះរាជក្រឹត្យ'),
        ),
        migrations.AddField(
            model_name='officermedalrequest',
            name='legal_doc_type',
            field=models.CharField(blank=True, choices=[('ROYAL_DECREE', 'ព្រះរាជក្រឹត្យ (ព្រះមហាក្សត្រ)'), ('ANUKRET', 'អនុក្រឹត្យ (រាជរដ្ឋាភិបាល)'), ('PRAKAS', 'ប្រកាស (ក្រសួង)'), ('DECISION', 'សេចក្តីសម្រេច / លិខិតផ្លូវការ'), ('OTHER', 'លិខិតបទដ្ឋានផ្សេងៗ')], max_length=50, verbose_name='ប្រភេទលិខិតបទដ្ឋាន'),
        ),
        migrations.AddField(
            model_name='officermedalrequest',
            name='ministry_decision_notes',
            field=models.TextField(blank=True, verbose_name='កំណត់សម្គាល់ការសម្រេចរបស់ក្រសួង'),
        ),
        migrations.AddField(
            model_name='officerpromotionrequest',
            name='effective_date',
            field=models.DateField(blank=True, null=True, verbose_name='កាលបរិច្ឆេទចូលជាធរមាន'),
        ),
        migrations.AddField(
            model_name='officerpromotionrequest',
            name='is_profile_updated',
            field=models.BooleanField(default=False, verbose_name='បាន Update Profile រួច'),
        ),
        migrations.AddField(
            model_name='officerpromotionrequest',
            name='legal_doc_date',
            field=models.DateField(blank=True, null=True, verbose_name='កាលបរិច្ឆេទចុះហត្ថលេខា'),
        ),
        migrations.AddField(
            model_name='officerpromotionrequest',
            name='legal_doc_number',
            field=models.CharField(blank=True, max_length=150, verbose_name='លេខប្រកាស/អនុក្រឹត្យ/ព្រះរាជក្រឹត្យ'),
        ),
        migrations.AddField(
            model_name='officerpromotionrequest',
            name='legal_doc_type',
            field=models.CharField(blank=True, choices=[('PRAKAS', 'ប្រកាស (ក្រសួង)'), ('ANUKRET', 'អនុក្រឹត្យ (រាជរដ្ឋាភិបាល)'), ('ROYAL_DECREE', 'ព្រះរាជក្រឹត្យ (ព្រះមហាក្សត្រ)'), ('DECISION', 'សេចក្តីសម្រេច / លិខិតផ្លូវការ'), ('OTHER', 'លិខិតបទដ្ឋានផ្សេងៗ')], max_length=50, verbose_name='ប្រភេទលិខិតបទដ្ឋាន'),
        ),
        migrations.AddField(
            model_name='officerpromotionrequest',
            name='ministry_decision_notes',
            field=models.TextField(blank=True, verbose_name='កំណត់សម្គាល់ការសម្រេចរបស់ក្រសួង'),
        ),
        migrations.AlterField(
            model_name='officermedalrequest',
            name='status',
            field=models.CharField(choices=[('PENDING', '🟡 រង់ចាំពិនិត្យ (Pending)'), ('DEPT_APPROVED', '🟢 ថ្នាក់ដឹកនាំមន្ទីរឯកភាព (Dept Approved)'), ('DEPT_REJECTED', '🔴 ថ្នាក់ដឹកនាំមន្ទីរមិនឯកភាព (Dept Rejected)'), ('SUBMITTED', '🏛️ បានបញ្ជូនទៅក្រសួង (Submitted)'), ('MINISTRY_APPROVED', '👑 ក្រសួងអនុម័តផ្លូវការ (Ministry Approved)'), ('MINISTRY_REJECTED', '❌ ក្រសួងមិនអនុម័ត/ធ្លាក់ (Ministry Rejected)'), ('APPROVED', '🟢 ថ្នាក់ដឹកនាំមន្ទីរឯកភាព (Approved)'), ('REJECTED', '🔴 មិនទាន់ឯកភាព (Rejected)')], default='PENDING', max_length=30, verbose_name='ស្ថានភាពពិនិត្យ'),
        ),
        migrations.AlterField(
            model_name='officerpromotionrequest',
            name='status',
            field=models.CharField(choices=[('PENDING', '🟡 រង់ចាំពិនិត្យ (Pending)'), ('DEPT_APPROVED', '🟢 ថ្នាក់ដឹកនាំមន្ទីរឯកភាព (Dept Approved)'), ('DEPT_REJECTED', '🔴 ថ្នាក់ដឹកនាំមន្ទីរមិនឯកភាព (Dept Rejected)'), ('SUBMITTED', '🏛️ បានបញ្ជូនទៅក្រសួង (Submitted)'), ('MINISTRY_APPROVED', '👑 ក្រសួងអនុម័តផ្លូវការ (Ministry Approved)'), ('MINISTRY_REJECTED', '❌ ក្រសួងមិនអនុម័ត/ធ្លាក់ (Ministry Rejected)'), ('APPROVED', '🟢 ថ្នាក់ដឹកនាំមន្ទីរឯកភាព (Approved)'), ('REJECTED', '🔴 មិនទាន់ឯកភាព (Rejected)')], default='PENDING', max_length=30, verbose_name='ស្ថានភាពពិនិត្យ'),
        ),
    ]
