# Generated by Django 5.2.17 on 2026-08-24 04:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dms', '0025_officermedalrequest_effective_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractOfficer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='contract_officers/photos/%Y/', verbose_name='រូបថត 4x6')),
                ('khmer_last_name', models.CharField(max_length=100, verbose_name='គោត្តនាម (ខ្មែរ)')),
                ('khmer_first_name', models.CharField(max_length=100, verbose_name='នាមខ្លួន (ខ្មែរ)')),
                ('latin_name', models.CharField(blank=True, max_length=150, verbose_name='អក្សរពុម្ពឡាតាំង (Latin Name)')),
                ('gender', models.CharField(choices=[('MALE', 'ប្រុស'), ('FEMALE', 'ស្រី')], default='MALE', max_length=10, verbose_name='ភេទ')),
                ('nationality', models.CharField(default='ខ្មែរ', max_length=50, verbose_name='សញ្ជាតិ')),
                ('ethnicity', models.CharField(blank=True, default='ខ្មែរ', max_length=50, verbose_name='ជនជាតិ')),
                ('dob', models.CharField(blank=True, max_length=150, verbose_name='ថ្ងៃខែឆ្នាំកំណើត')),
                ('pob_province_code', models.CharField(blank=True, max_length=20, null=True, verbose_name='កូដរាជធានី/ខេត្តកំណើត')),
                ('pob_district_code', models.CharField(blank=True, max_length=20, null=True, verbose_name='កូដស្រុក/ខណ្ឌកំណើត')),
                ('pob_commune_code', models.CharField(blank=True, max_length=20, null=True, verbose_name='កូដឃុំ/សង្កាត់កំណើត')),
                ('pob_village_code', models.CharField(blank=True, max_length=20, null=True, verbose_name='កូដភូមិកំណើត')),
                ('pob_village', models.CharField(blank=True, max_length=100, verbose_name='ភូមិកំណើត')),
                ('pob_commune', models.CharField(blank=True, max_length=100, verbose_name='ឃុំ/សង្កាត់កំណើត')),
                ('pob_district', models.CharField(blank=True, max_length=100, verbose_name='ស្រុក/ខណ្ឌកំណើត')),
                ('pob_province', models.CharField(blank=True, max_length=100, verbose_name='រាជធានី/ខេត្តកំណើត')),
                ('place_of_birth', models.CharField(blank=True, max_length=255, verbose_name='ទីកន្លែងកំណើត (សង្ខេប)')),
                ('general_education', models.CharField(blank=True, max_length=200, verbose_name='កម្រិតវប្បធម៌ទូទៅ')),
                ('training_level', models.CharField(blank=True, max_length=200, verbose_name='កម្រិតបណ្តុះបណ្តាល')),
                ('skill_specialization', models.CharField(blank=True, max_length=200, verbose_name='ជំនាញ/ឯកទេស')),
                ('id_type', models.CharField(choices=[('NATIONAL_ID', 'អត្តសញ្ញាណប័ណ្ណសញ្ជាតិខ្មែរ'), ('PASSPORT', 'លិខិតឆ្លងដែន')], default='NATIONAL_ID', max_length=20, verbose_name='ប្រភេទឯកសារសម្គាល់ខ្លួន')),
                ('id_number', models.CharField(blank=True, max_length=100, verbose_name='លេខអត្តសញ្ញាណប័ណ្ណ ឬ លិខិតឆ្លងដែន')),
                ('working_unit', models.CharField(blank=True, max_length=255, verbose_name='អង្គភាព/ការិយាល័យបំពេញការងារ')),
                ('current_province_code', models.CharField(blank=True, max_length=20, null=True, verbose_name='កូដរាជធានី/ខេត្តបច្ចុប្បន្ន')),
                ('current_district_code', models.CharField(blank=True, max_length=20, null=True, verbose_name='កូដស្រុក/ខណ្ឌបច្ចុប្បន្ន')),
                ('current_commune_code', models.CharField(blank=True, max_length=20, null=True, verbose_name='កូដឃុំ/សង្កាត់បច្ចុប្បន្ន')),
                ('current_village_code', models.CharField(blank=True, max_length=20, null=True, verbose_name='កូដភូមិបច្ចុប្បន្ន')),
                ('current_house_no', models.CharField(blank=True, max_length=50, verbose_name='ផ្ទះលេខ (បច្ចុប្បន្ន)')),
                ('current_street', models.CharField(blank=True, max_length=100, verbose_name='ផ្លូវ (បច្ចុប្បន្ន)')),
                ('current_village', models.CharField(blank=True, max_length=100, verbose_name='ភូមិ (បច្ចុប្បន្ន)')),
                ('current_commune', models.CharField(blank=True, max_length=100, verbose_name='ឃុំ/សង្កាត់ (បច្ចុប្បន្ន)')),
                ('current_district', models.CharField(blank=True, max_length=100, verbose_name='ស្រុក/ខណ្ឌ (បច្ចុប្បន្ន)')),
                ('current_province', models.CharField(blank=True, max_length=100, verbose_name='រាជធានី/ខេត្ត (បច្ចុប្បន្ន)')),
                ('current_address', models.CharField(blank=True, max_length=255, verbose_name='អាសយដ្ឋានបច្ចុប្បន្ន (សង្ខេប)')),
                ('phone', models.CharField(blank=True, max_length=100, verbose_name='លេខទូរស័ព្ទ')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='អ៊ីម៉ែល (បើមាន)')),
                ('position_title', models.CharField(default='មន្ត្រីជាប់កិច្ចសន្យា', max_length=150, verbose_name='មុខតំណែង/តួនាទី')),
                ('contract_number', models.CharField(blank=True, max_length=100, verbose_name='លេខកិច្ចសន្យា/លេខលិខិត')),
                ('contract_start_date', models.DateField(blank=True, null=True, verbose_name='កាលបរិច្ឆេទចាប់ផ្តើមកិច្ចសន្យា')),
                ('contract_end_date', models.DateField(blank=True, null=True, verbose_name='កាលបរិច្ឆេទផុតកំណត់កិច្ចសន្យា')),
                ('salary', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='ប្រាក់បៀវត្ស/ប្រាក់ឧបត្ថម្ភ (៛)')),
                ('contract_status', models.CharField(choices=[('ACTIVE', 'កំពុងបម្រើការ'), ('RENEWED', 'បានបន្តកិច្ចសន្យា'), ('EXPIRED', 'ផុតកិច្ចសន្យា'), ('TERMINATED', 'បានបញ្ឈប់/ឈប់')], default='ACTIVE', max_length=20, verbose_name='ស្ថានភាពកិច្ចសន្យា')),
                ('contract_file', models.FileField(blank=True, null=True, upload_to='contract_officers/contracts/%Y/', verbose_name='ឯកសារកិច្ចសន្យា (PDF/រូបភាព)')),
                ('remarks', models.TextField(blank=True, verbose_name='កំណត់សម្គាល់បន្ថែម')),
                ('is_active', models.BooleanField(default=True, verbose_name='សកម្ម')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ថ្ងៃបង្កើត')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='ថ្ងៃកែប្រែចុងក្រោយ')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_contract_officers', to=settings.AUTH_USER_MODEL, verbose_name='អ្នកបញ្ចូលទិន្នន័យ')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contract_officers', to='dms.department', verbose_name='ការិយាល័យ/អង្គភាពបច្ចុប្បន្ន')),
            ],
            options={
                'verbose_name': 'មន្ត្រីជាប់កិច្ចសន្យា',
                'verbose_name_plural': 'បញ្ជីមន្ត្រីជាប់កិច្ចសន្យា',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContractOfficerAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='ឈ្មោះឯកសារ')),
                ('file', models.FileField(upload_to='contract_officers/attachments/%Y/%m/', verbose_name='ឯកសារភ្ជាប់')),
                ('file_type', models.CharField(blank=True, max_length=50, verbose_name='ប្រភេទឯកសារ')),
                ('notes', models.TextField(blank=True, verbose_name='កំណត់សម្គាល់')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='កាលបរិច្ឆេទបញ្ចូល')),
                ('contract_officer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='dms.contractofficer', verbose_name='មន្ត្រីជាប់កិច្ចសន្យា')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='អ្នកបញ្ចូល')),
            ],
            options={
                'verbose_name': 'ឯកសារភ្ជាប់មន្ត្រីកិច្ចសន្យា',
                'verbose_name_plural': 'បញ្ជីឯកសារភ្ជាប់មន្ត្រីកិច្ចសន្យា',
                'ordering': ['-created_at'],
            },
        ),
    ]
