# Generated by Django 6.1 on 2026-08-24 16:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dms', '0027_vehicle_vehiclerequest_vehiclerequestattachment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contractofficer',
            options={'ordering': ['-contract_year', '-created_at'], 'verbose_name': 'មន្ត្រីជាប់កិច្ចសន្យា', 'verbose_name_plural': 'បញ្ជីមន្ត្រីជាប់កិច្ចសន្យា'},
        ),
        migrations.AddField(
            model_name='contractofficer',
            name='contract_count_years',
            field=models.PositiveIntegerField(default=1, verbose_name='ចំនួនឆ្នាំដែលបានបម្រើការ/បន្ត'),
        ),
        migrations.AddField(
            model_name='contractofficer',
            name='contract_year',
            field=models.PositiveIntegerField(default=2026, verbose_name='ឆ្នាំកិច្ចសន្យា'),
        ),
        migrations.AddField(
            model_name='contractofficer',
            name='last_renewed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='កាលបរិច្ឆេទអនុម័តបន្តចុងក្រោយ'),
        ),
        migrations.AddField(
            model_name='contractofficer',
            name='last_renewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='renewed_contract_officers', to=settings.AUTH_USER_MODEL, verbose_name='អ្នកអនុម័តបន្ត'),
        ),
        migrations.AddField(
            model_name='contractofficer',
            name='original_join_year',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='ឆ្នាំចាប់ផ្តើមដំបូង'),
        ),
        migrations.CreateModel(
            name='ContractOfficerRenewalHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_year', models.PositiveIntegerField(verbose_name='ពីឆ្នាំកិច្ចសន្យា')),
                ('to_year', models.PositiveIntegerField(verbose_name='ទៅឆ្នាំកិច្ចសន្យាថ្មី')),
                ('contract_number', models.CharField(blank=True, max_length=100, verbose_name='លេខកិច្ចសន្យាថ្មី')),
                ('contract_start_date', models.DateField(blank=True, null=True, verbose_name='កាលបរិច្ឆេទចាប់ផ្តើមកិច្ចសន្យាថ្មី')),
                ('contract_end_date', models.DateField(blank=True, null=True, verbose_name='កាលបរិច្ឆេទផុតកំណត់កិច្ចសន្យាថ្មី')),
                ('salary', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='ប្រាក់បៀវត្ស/ប្រាក់ឧបត្ថម្ភ (៛)')),
                ('position_title', models.CharField(blank=True, max_length=150, verbose_name='មុខតំណែង/តួនាទីថ្មី')),
                ('working_unit', models.CharField(blank=True, max_length=255, verbose_name='អង្គភាព/ការិយាល័យថ្មី')),
                ('renewal_document', models.FileField(blank=True, null=True, upload_to='contract_officers/renewals/%Y/', verbose_name='ឯកសារកិច្ចសន្យាថ្មី (PDF/រូបភាព)')),
                ('remarks', models.TextField(blank=True, verbose_name='កំណត់សម្គាល់បន្ថែម')),
                ('approved_at', models.DateTimeField(auto_now_add=True, verbose_name='កាលបរិច្ឆេទអនុម័ត')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='អ្នកអនុម័ត')),
                ('contract_officer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='renewals', to='dms.contractofficer', verbose_name='មន្ត្រីជាប់កិច្ចសន្យា')),
            ],
            options={
                'verbose_name': 'ប្រវត្តិបន្តកិច្ចសន្យា',
                'verbose_name_plural': 'បញ្ជីប្រវត្តិបន្តកិច្ចសន្យា',
                'ordering': ['-to_year', '-approved_at'],
            },
        ),
    ]
