# Generated by Django 6.1 on 2026-08-24 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dms', '0028_alter_contractofficer_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='position_title',
            field=models.CharField(blank=True, choices=[('ប្រធានមន្ទីរ', 'ប្រធានមន្ទីរ'), ('អនុប្រធានមន្ទីរ', 'អនុប្រធានមន្ទីរ'), ('នាយខណ្ឌ', 'នាយខណ្ឌ'), ('នាយរងខណ្ឌ', 'នាយរងខណ្ឌ'), ('ប្រធានការិយាល័យ', 'ប្រធានការិយាល័យ'), ('អនុប្រធានការិយាល័យ', 'អនុប្រធានការិយាល័យ'), ('នាយផ្នែក', 'នាយផ្នែក'), ('នាយរងផ្នែក', 'នាយរងផ្នែក'), ('មន្ត្រី', 'មន្ត្រី')], default='មន្ត្រី', max_length=150, verbose_name='មុខតំណែង'),
        ),
    ]
