# Generated by Django 5.2.17 on 2026-08-25 03:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dms', '0029_alter_userprofile_position_title'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractOfficerTransferHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_working_unit', models.CharField(blank=True, max_length=255, verbose_name='អង្គភាព/ការិយាល័យចាស់')),
                ('to_working_unit', models.CharField(blank=True, max_length=255, verbose_name='អង្គភាព/ការិយាល័យថ្មី')),
                ('from_position_title', models.CharField(blank=True, max_length=150, verbose_name='មុខតំណែងចាស់')),
                ('to_position_title', models.CharField(blank=True, max_length=150, verbose_name='មុខតំណែងថ្មី')),
                ('transfer_date', models.DateField(blank=True, null=True, verbose_name='កាលបរិច្ឆេទផ្ទេរ/ចូលកាន់តំណែង')),
                ('reference_letter_number', models.CharField(blank=True, max_length=150, verbose_name='លេខលិខិតផ្ទេរ/ចាត់តាំង')),
                ('transfer_document', models.FileField(blank=True, null=True, upload_to='contract_officers/transfers/%Y/', verbose_name='ឯកសារលិខិតផ្ទេរ (PDF/រូបភាព)')),
                ('remarks', models.TextField(blank=True, verbose_name='មូលហេតុ/កំណត់សម្គាល់បន្ថែម')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='កាលបរិច្ឆេទកត់ត្រា')),
                ('contract_officer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='dms.contractofficer', verbose_name='មន្ត្រីជាប់កិច្ចសន្យា')),
                ('from_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contract_transfers_from', to='dms.department', verbose_name='ពីការិយាល័យ/ខណ្ឌ')),
                ('to_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contract_transfers_to', to='dms.department', verbose_name='ទៅការិយាល័យ/ខណ្ឌថ្មី')),
                ('transferred_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_contract_transfers', to=settings.AUTH_USER_MODEL, verbose_name='អ្នកធ្វើការផ្លាស់ប្តូរ (Admin)')),
            ],
            options={
                'verbose_name': 'ប្រវត្តិផ្លាស់ប្តូរការិយាល័យមន្ត្រីកិច្ចសន្យា',
                'verbose_name_plural': 'បញ្ជីប្រវត្តិផ្លាស់ប្តូរការិយាល័យមន្ត្រីកិច្ចសន្យា',
                'ordering': ['-transfer_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OfficerDepartmentTransferHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_position_title', models.CharField(blank=True, max_length=150, verbose_name='មុខតំណែងចាស់')),
                ('to_position_title', models.CharField(blank=True, max_length=150, verbose_name='មុខតំណែងថ្មី')),
                ('transfer_date', models.DateField(blank=True, null=True, verbose_name='កាលបរិច្ឆេទផ្ទេរ/ចូលកាន់តំណែង')),
                ('reference_letter_number', models.CharField(blank=True, max_length=150, verbose_name='លេខលិខិតផ្ទេរ/ចាត់តាំង')),
                ('transfer_document', models.FileField(blank=True, null=True, upload_to='officers/transfers/%Y/', verbose_name='ឯកសារលិខិតផ្ទេរ (PDF/រូបភាព)')),
                ('remarks', models.TextField(blank=True, verbose_name='មូលហេតុ/កំណត់សម្គាល់បន្ថែម')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='កាលបរិច្ឆេទកត់ត្រា')),
                ('from_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='officer_transfers_from', to='dms.department', verbose_name='ពីការិយាល័យ/ខណ្ឌ')),
                ('officer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_transfers', to='dms.civilservantprofile', verbose_name='មន្ត្រីរាជការ')),
                ('to_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='officer_transfers_to', to='dms.department', verbose_name='ទៅការិយាល័យ/ខណ្ឌថ្មី')),
                ('transferred_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_officer_transfers', to=settings.AUTH_USER_MODEL, verbose_name='អ្នកធ្វើការផ្លាស់ប្តូរ (Admin)')),
            ],
            options={
                'verbose_name': 'ប្រវត្តិផ្លាស់ប្តូរការិយាល័យមន្ត្រីរាជការ',
                'verbose_name_plural': 'បញ្ជីប្រវត្តិផ្លាស់ប្តូរការិយាល័យមន្ត្រីរាជការ',
                'ordering': ['-transfer_date', '-created_at'],
            },
        ),
    ]
