# Generated by Django 5.2.17 on 2026-08-25 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dms', '0030_contractofficertransferhistory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='civilservantprofile',
            name='framework_category',
            field=models.CharField(blank=True, choices=[('A', 'ក្របខ័ណ្ឌ ក (ក) - ឧត្តមមន្ត្រី / បច្ចេកទេសជាន់ខ្ពស់'), ('B', 'ក្របខ័ណ្ឌ ខ (ខ) - វរមន្ត្រី / បច្ចេកទេសមធ្យម'), ('C', 'ក្របខ័ណ្ឌ គ (គ) - អនុមន្ត្រី / បច្ចេកទេសបឋម'), ('D', 'ក្របខ័ណ្ឌ ឃ (ឃ) - មន្ត្រី / ជំនួយការ')], max_length=10, null=True, verbose_name='ប្រភេទក្របខ័ណ្ឌ (ក, ខ, គ, ឃ)'),
        ),
        migrations.AddField(
            model_name='civilservantprofile',
            name='highest_degree',
            field=models.CharField(blank=True, choices=[('DOCTORATE', '(១). បណ្ឌិត (Doctorate / PhD)'), ('MASTER', '(២). បរិញ្ញាបត្រជាន់ខ្ពស់ / អនុបណ្ឌិត (Master)'), ('BACHELOR', '(៣). បរិញ្ញាប័ត្រ (Bachelor)'), ('ASSOCIATE', '(៤). បរិញ្ញាប័ត្ររង (Associate)'), ('HIGHSCHOOL', '(៥). មធ្យមសិក្សាទុតិយភូមិ / បាក់ឌុប (High School)'), ('OTHER', '(៦). ផ្សេងៗ (Other / Secondary / Primary / None)')], max_length=30, null=True, verbose_name='កម្រិតសញ្ញាបត្រខ្ពស់បំផុត'),
        ),
        migrations.AddField(
            model_name='civilservantprofile',
            name='officer_status',
            field=models.CharField(choices=[('ACTIVE', '១. មន្ត្រីសកម្ម (Active)'), ('UNPAID_LEAVE', '២. មន្ត្រីស្ថិតក្នុងភាពទំនេរគ្មានបៀវត្ស (Unpaid Leave)'), ('OUTSIDE_FRAMEWORK', '៣. មន្ត្រីស្ថិតនៅក្រៅក្របខណ្ឌដើម (Outside Framework)'), ('DISMISSED', '៤. មន្ត្រីត្រូវបានលុបឈ្មោះ (Dismissed)'), ('RETIRED', '៥. មន្ត្រីចូលនិវត្តន៍ (Retired)'), ('TRAINEE', '៦. មន្ត្រីកម្មសិក្សា (Trainee/Probation)'), ('TRANSFERRED_OUT', '៧. មន្ត្រីផ្ទេរចេញ (Transferred Out)')], default='ACTIVE', max_length=30, verbose_name='ស្ថានភាពមន្ត្រី (គិតមកដល់បច្ចុប្បន្ន)'),
        ),
    ]
