# Generated by Django 5.2.17 on 2026-08-26 07:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dms', '0031_civilservantprofile_framework_category_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='កាលបរិច្ឆេទ')),
                ('person_type', models.CharField(choices=[('CIVIL_SERVANT', 'មន្ត្រីរាជការ'), ('CONTRACT_OFFICER', 'មន្ត្រីជាប់កិច្ចសន្យា')], default='CIVIL_SERVANT', max_length=20, verbose_name='ប្រភេទបុគ្គលិក')),
                ('position_title', models.CharField(blank=True, max_length=150, verbose_name='មុខតំណែង/តួនាទី')),
                ('morning_in', models.BooleanField(default=True, verbose_name='ព្រឹក ចូល')),
                ('morning_out', models.BooleanField(default=True, verbose_name='ព្រឹក ចេញ')),
                ('afternoon_in', models.BooleanField(default=True, verbose_name='ល្ងាច ចូល')),
                ('afternoon_out', models.BooleanField(default=True, verbose_name='ល្ងាច ចេញ')),
                ('status', models.CharField(choices=[('PRESENT', 'វត្តមាន (Present)'), ('MISSION', 'M - បេសកកម្ម (Mission)'), ('LEAVE_PERMISSION', 'P - មានច្បាប់ (Leave with Permission)'), ('ABSENT_NO_LEAVE', 'A - អត់ច្បាប់ (Absent without Leave)'), ('UNPAID_LEAVE', 'ទំនេរគ្មានបៀវត្ស (Unpaid Leave)')], default='PRESENT', max_length=30, verbose_name='ស្ថានភាពវត្តមាន')),
                ('is_late', models.BooleanField(default=False, verbose_name='មកយឺត')),
                ('is_early_out', models.BooleanField(default=False, verbose_name='ចេញមុន')),
                ('leave_type', models.CharField(blank=True, choices=[('', '--- គ្មាន / មិនបានឈប់ ---'), ('ANNUAL', '១-ច្បាប់ឈប់ប្រចាំឆ្នាំ (១៥ថ្ងៃ/១ឆ្នាំ)'), ('SHORT', '២-ច្បាប់ឈប់រយៈពេលខ្លី (១៥ថ្ងៃ/១ឆ្នាំ)'), ('MATERNITY', '៣-ច្បាប់ឈប់សម្រាកលំហែមាតុភាព (៣ខែ)'), ('SICK', '៤-ច្បាប់ឈប់សម្រាកព្យាបាលជំងឺ (១២ខែ)'), ('PERSONAL', '៥-ច្បាប់ឈប់សម្រាកដោយមានកិច្ចការផ្ទាល់ខ្លួន (៣ខែ)'), ('OTHER', 'ផ្សេងៗ')], default='', max_length=30, verbose_name='ប្រភេទច្បាប់ឈប់សម្រាក')),
                ('reference_doc', models.CharField(blank=True, max_length=255, verbose_name='លិខិតបញ្ជាក់/យោង')),
                ('disciplinary_measure', models.CharField(blank=True, max_length=255, verbose_name='វិធានការ/ទណ្ឌកម្មវិន័យ')),
                ('remarks', models.TextField(blank=True, verbose_name='ផ្សេងៗ/កំណត់សម្គាល់')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contract_officer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='dms.contractofficer', verbose_name='មន្ត្រីជាប់កិច្ចសន្យា')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='dms.department', verbose_name='ការិយាល័យ/ខណ្ឌ')),
                ('officer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='dms.civilservantprofile', verbose_name='មន្ត្រីរាជការ')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_attendances', to=settings.AUTH_USER_MODEL, verbose_name='អ្នកកត់ត្រា')),
            ],
            options={
                'verbose_name': 'កំណត់ត្រាវត្តមាន',
                'verbose_name_plural': 'បញ្ជីកំណត់ត្រាវត្តមាន',
                'ordering': ['-date', 'department'],
            },
        ),
    ]
