# Generated by Django 5.2.17 on 2026-09-03 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dms', '0032_attendancerecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='can_export_contract_excel',
            field=models.BooleanField(default=False, verbose_name='សិទ្ធិទាញយក Excel មន្ត្រីកិច្ចសន្យា (Export Contract Staff to Excel)'),
        ),
    ]
