# Generated by Django 5.2.17 on 2026-09-03 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dms', '0033_userprofile_can_export_contract_excel'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='can_export_civil_servant_excel',
            field=models.BooleanField(default=False, verbose_name='សិទ្ធិទាញយក Excel បញ្ជីរាយនាមមន្ត្រី (Export Civil Servants to Excel)'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_view_e2_report',
            field=models.BooleanField(default=False, verbose_name='សិទ្ធិមើលនិងទាញយកទម្រង់ E-2 ថ្នាក់ខេត្ត (Access Form E-2)'),
        ),
    ]
