# Generated by Django 5.2.17 on 2026-09-16 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dms', '0034_userprofile_can_export_civil_servant_excel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='officerpromotionrequest',
            name='average_score',
            field=models.CharField(blank=True, max_length=50, verbose_name='ពិន្ទុមធ្យមភាគ'),
        ),
        migrations.AddField(
            model_name='officerpromotionrequest',
            name='bulletin_custom_data',
            field=models.JSONField(blank=True, default=dict, verbose_name='ទិន្នន័យកែសម្រួលបន្ថែមសម្រាប់ព្រឹត្តិប័ត្រ'),
        ),
        migrations.AddField(
            model_name='officerpromotionrequest',
            name='grade',
            field=models.CharField(blank=True, max_length=50, verbose_name='និទ្ទេស'),
        ),
        migrations.AddField(
            model_name='officerpromotionrequest',
            name='minister_comment',
            field=models.TextField(blank=True, verbose_name='ចំណារ ឬ មូលវិចារណ៍របស់រដ្ឋមន្ត្រី ឬប្រធានស្ថាប័នមានសមត្ថកិច្ច'),
        ),
        migrations.AddField(
            model_name='officerpromotionrequest',
            name='scores_data',
            field=models.JSONField(blank=True, default=dict, verbose_name='ទិន្នន័យពិន្ទុតាមលក្ខណៈវិនិច្ឆ័យនីមួយៗ'),
        ),
        migrations.AddField(
            model_name='officerpromotionrequest',
            name='template_code',
            field=models.CharField(blank=True, default='D01', max_length=20, verbose_name='កម្រងក្របខណ្ឌ (D01, D02, D03)'),
        ),
        migrations.AddField(
            model_name='officerpromotionrequest',
            name='unit_head_comment',
            field=models.TextField(blank=True, verbose_name='ចំណារ ឬ មូលវិចារណ៍របស់ប្រធានស្ថាប័ន ឬអង្គភាពផ្ទាល់'),
        ),
        migrations.AddField(
            model_name='officerpromotionrequest',
            name='unit_proposal',
            field=models.CharField(blank=True, max_length=255, verbose_name='សំណើរបស់ប្រធានអង្គភាព (ស្នើសុំដំឡើងថ្នាក់)'),
        ),
    ]
