from django.urls import path
from . import views

urlpatterns = [
    path('', views.dashboard, name='dashboard'),
    path('login/', views.login_view, name='login'),
    path('register/', views.register_view, name='register'),
    path('verify-otp/', views.otp_verify_view, name='otp_verify'),
    path('resend-otp/', views.otp_resend_view, name='otp_resend'),
    path('logout/', views.logout_view, name='logout'),
    
    path('documents/', views.document_list, name='document_list'),
    path('documents/inbound/', views.inbound_documents_view, name='inbound_documents'),
    path('documents/outbound/', views.outbound_documents_view, name='outbound_documents'),
    path('documents/my-department/', views.my_department_documents_view, name='my_department_documents'),
    path('documents/new/', views.document_create, name='document_create'),
    path('documents/<int:pk>/', views.document_detail, name='document_detail'),
    path('documents/<int:pk>/version/add/', views.document_version_add, name='document_version_add'),
    path('documents/<int:pk>/version/<int:version_id>/download/', views.document_version_download, name='document_version_download'),
    path('documents/<int:pk>/version/<int:version_id>/view/', views.document_version_view, name='document_version_view'),
    path('documents/<int:pk>/annotate/', views.annotate_document, name='annotate_document'),
    path('documents/<int:pk>/route/', views.route_document, name='route_document'),
    path('documents/<int:pk>/route/cancel/<int:routing_id>/', views.cancel_route_document, name='cancel_route_document'),
    path('documents/<int:pk>/complete/', views.complete_document, name='complete_document'),
    path('documents/<int:pk>/delete/', views.document_delete, name='document_delete'),
    path('documents/<int:pk>/print/', views.document_print, name='document_print'),

    # Internal Department Live Chat
    path('chat/', views.live_chat_view, name='live_chat'),
    path('chat/api/send/', views.send_chat_api, name='send_chat_api'),
    path('chat/api/messages/', views.get_chat_messages_api, name='get_chat_messages_api'),
    path('chat/api/check-unread/', views.check_new_chat_notifications_api, name='check_new_chat_notifications_api'),
    path('chat/api/edit/<int:pk>/', views.edit_chat_message_api, name='edit_chat_message_api'),
    path('chat/api/delete/<int:pk>/', views.delete_chat_message_api, name='delete_chat_message_api'),
    
    path('reports/', views.reports_view, name='reports'),
    path('reports/export/excel/', views.export_excel_report, name='export_excel_report'),
    
    path('notifications/<int:pk>/read/', views.mark_notification_read, name='mark_notification_read'),
    path('notifications/read-all/', views.mark_all_notifications_read, name='mark_all_notifications_read'),

    # User Management and Approvals
    path('users/approvals/', views.user_approvals_view, name='user_approvals'),
    path('users/<int:user_id>/edit/', views.user_edit_view, name='user_edit'),
    path('users/<int:user_id>/approve/', views.user_approve_action, name='user_approve_action'),
    path('users/<int:user_id>/revoke/', views.user_revoke_action, name='user_revoke_action'),
    path('users/<int:user_id>/delete/', views.user_delete_action, name='user_delete_action'),
    
    # Dev Phase: Quick Switch to User & Switch Back
    path('dev/switch-user/<int:user_id>/', views.dev_switch_user, name='dev_switch_user'),
    path('dev/switch-back-admin/', views.dev_switch_back_admin, name='dev_switch_back_admin'),

    # Department and Organization Structure Management
    path('departments/', views.department_list_view, name='department_list_manage'),
    path('departments/<int:pk>/edit/', views.department_edit_view, name='department_edit'),
    path('departments/<int:pk>/toggle-active/', views.department_toggle_active_view, name='department_toggle_active'),
    path('departments/switch-structure/', views.department_switch_structure_view, name='department_switch_structure'),
    path('departments/<int:pk>/delete/', views.department_delete_view, name='department_delete'),

    # 👥 Civil Servant Profile & HR Management (ជីវប្រវត្តិមន្ត្រីរាជការ)
    path('officers/', views.officer_list, name='officer_list'),
    path('officers/status-report/', views.officer_status_report_view, name='officer_status_report'),
    path('officers/status-report/print/', views.officer_status_report_print_view, name='officer_status_report_print'),
    path('officers/status-report/export/excel/', views.officer_status_export_excel, name='officer_status_export_excel'),
    path('officers/status-report/api/update-status/', views.api_officer_status_update, name='api_officer_status_update'),
    path('officers/new/', views.officer_create, name='officer_create'),
    path('officers/import-docx/', views.officer_import_docx, name='officer_import_docx'),
    path('officers/batch-photos/officers-index/', views.api_officers_for_photo_match, name='api_officers_for_photo_match'),
    path('officers/batch-photos/upload/', views.officer_batch_upload_photo_single, name='officer_batch_upload_photo_single'),
    # 👥 HR Tracking Individual Modules (៣ មុខងារតាមដានដាច់ដោយឡែក)
    path('officers/retirement/', views.officer_retirement_view, name='officer_retirement'),
    path('officers/retirement/export/excel/', views.officer_retirement_export_excel, name='officer_retirement_export_excel'),
    
    path('officers/promotion/', views.officer_promotion_view, name='officer_promotion'),
    path('officers/promotion/export/excel/', views.officer_promotion_export_excel, name='officer_promotion_export_excel'),
    path('officers/promotion/master/excel/', views.officer_promotion_master_export_excel, name='officer_promotion_master_export_excel'),
    path('officers/promotion/master/print/', views.officer_promotion_master_print_view, name='officer_promotion_master_print_view'),
    path('officers/promotion/batch-update/', views.officer_promotion_batch_status_update, name='officer_promotion_batch_status_update'),
    path('officers/promotion/requests/create/', views.officer_promotion_request_create, name='officer_promotion_request_create'),
    path('officers/promotion/requests/<int:pk>/edit/', views.officer_promotion_request_edit, name='officer_promotion_request_edit'),
    path('officers/promotion/requests/<int:pk>/review/', views.officer_promotion_request_review, name='officer_promotion_request_review'),
    path('officers/promotion/requests/<int:pk>/delete/', views.officer_promotion_request_delete, name='officer_promotion_request_delete'),
    
    path('officers/medals/', views.officer_medals_view, name='officer_medals'),
    path('officers/medals/export/excel/', views.officer_medals_export_excel, name='officer_medals_export_excel'),
    path('officers/medals/master/excel/', views.officer_medals_master_export_excel, name='officer_medals_master_export_excel'),
    path('officers/medals/master/print/', views.officer_medals_master_print_view, name='officer_medals_master_print_view'),
    path('officers/medals/batch-update/', views.officer_medals_batch_status_update, name='officer_medals_batch_status_update'),
    path('officers/medals/requests/create/', views.officer_medal_request_create, name='officer_medal_request_create'),
    path('officers/medals/requests/<int:pk>/edit/', views.officer_medal_request_edit, name='officer_medal_request_edit'),
    path('officers/medals/requests/<int:pk>/review/', views.officer_medal_request_review, name='officer_medal_request_review'),
    path('officers/medals/requests/<int:pk>/delete/', views.officer_medal_request_delete, name='officer_medal_request_delete'),
    path('officers/tracking/', views.officer_tracking_view, name='officer_tracking'),
    path('officers/tracking/retirement/', views.officer_tracking_retirement_view, name='officer_tracking_retirement'),
    path('officers/tracking/promotion/', views.officer_tracking_promotion_view, name='officer_tracking_promotion'),
    path('officers/tracking/medals/', views.officer_tracking_medals_view, name='officer_tracking_medals'),
    path('officers/tracking/export/excel/', views.officer_retirement_export_excel, name='officer_tracking_export_excel'),
    path('officers/settings/window/', views.officer_edit_window_setting_view, name='officer_edit_window_setting'),
    path('officers/bulk-delete/', views.officer_bulk_delete, name='officer_bulk_delete'),
    path('officers/delete-all/', views.officer_delete_all, name='officer_delete_all'),
    path('officers/<int:pk>/', views.officer_detail, name='officer_detail'),
    path('officers/<int:pk>/edit/', views.officer_edit, name='officer_edit'),
    path('officers/<int:pk>/print/', views.officer_print, name='officer_print'),
    path('officers/<int:pk>/delete/', views.officer_delete, name='officer_delete'),
    path('officers/export/excel/', views.officer_export_excel, name='officer_export_excel'),
    path('officers/preview/e1/', views.officer_preview_pdf_e1, name='officer_preview_pdf_e1'),
    path('officers/preview/e2/', views.officer_preview_pdf_e2, name='officer_preview_pdf_e2'),

    # 📎 Officer Reference Attachments & Audit Log
    path('officers/<int:pk>/attachments/add/', views.officer_attachment_add, name='officer_attachment_add'),
    path('officers/<int:pk>/attachments/<int:attachment_id>/edit/', views.officer_attachment_edit, name='officer_attachment_edit'),
    path('officers/<int:pk>/attachments/<int:attachment_id>/delete/', views.officer_attachment_delete, name='officer_attachment_delete'),
    path('officers/<int:pk>/attachments/<int:attachment_id>/view/', views.officer_attachment_view, name='officer_attachment_view'),
    path('officers/<int:pk>/attachments/<int:attachment_id>/download/', views.officer_attachment_download, name='officer_attachment_download'),
    path('officers/<int:pk>/transfer/', views.officer_transfer, name='officer_transfer'),
    path('officers/<int:pk>/transfers/<int:transfer_id>/delete/', views.officer_transfer_delete, name='officer_transfer_delete'),
    path('officers/audit-logs/', views.officer_audit_trail_view, name='officer_audit_trail'),
    path('officers/audit-logs/clear-all/', views.officer_audit_trail_clear_all, name='officer_audit_trail_clear_all'),
    path('officers/audit-logs/bulk-delete/', views.officer_audit_trail_bulk_delete, name='officer_audit_trail_bulk_delete'),
    path('officers/audit-logs/<int:log_id>/delete/', views.officer_audit_log_delete, name='officer_audit_log_delete'),

    # 📝 Contract Civil Servants & Staff (មន្ត្រីជាប់កិច្ចសន្យា)
    path('contract-officers/', views.contract_officer_list, name='contract_officer_list'),
    path('contract-officers/new/', views.contract_officer_create, name='contract_officer_create'),
    path('contract-officers/import-docx/', views.contract_officer_import_docx, name='contract_officer_import_docx'),
    path('contract-officers/api/scan/', views.api_contract_officer_scan_file, name='api_contract_officer_scan_file'),
    path('contract-officers/confirm-scan-import/', views.contract_officer_confirm_scan_import, name='contract_officer_confirm_scan_import'),
    path('contract-officers/api/save-gemini-key/', views.api_save_gemini_api_key, name='api_save_gemini_api_key'),
    path('contract-officers/<int:pk>/', views.contract_officer_detail, name='contract_officer_detail'),
    path('contract-officers/<int:pk>/edit/', views.contract_officer_edit, name='contract_officer_edit'),
    path('contract-officers/<int:pk>/renew/', views.contract_officer_renew, name='contract_officer_renew'),
    path('contract-officers/batch-renew/', views.contract_officer_batch_renew, name='contract_officer_batch_renew'),
    path('contract-officers/<int:pk>/transfer/', views.contract_officer_transfer, name='contract_officer_transfer'),
    path('contract-officers/<int:pk>/transfers/<int:transfer_id>/delete/', views.contract_officer_transfer_delete, name='contract_officer_transfer_delete'),
    path('contract-officers/<int:pk>/print/', views.contract_officer_print, name='contract_officer_print'),
    path('contract-officers/<int:pk>/delete/', views.contract_officer_delete, name='contract_officer_delete'),
    path('contract-officers/bulk-delete/', views.contract_officer_bulk_delete, name='contract_officer_bulk_delete'),
    path('contract-officers/export/excel/', views.contract_officer_export_excel, name='contract_officer_export_excel'),
    path('contract-officers/preview/d1/', views.contract_officer_preview_pdf_d1, name='contract_officer_preview_pdf_d1'),
    path('contract-officers/<int:pk>/attachments/add/', views.contract_officer_attachment_add, name='contract_officer_attachment_add'),
    path('contract-officers/<int:pk>/attachments/<int:attachment_id>/delete/', views.contract_officer_attachment_delete, name='contract_officer_attachment_delete'),
    path('contract-officers/<int:pk>/attachments/<int:attachment_id>/view/', views.contract_officer_attachment_view, name='contract_officer_attachment_view'),
    path('contract-officers/<int:pk>/attachments/<int:attachment_id>/download/', views.contract_officer_attachment_download, name='contract_officer_attachment_download'),

    # 🗺️ Cambodia Geography API (Cascading Address Selector & Admin Management)
    path('settings/geography/', views.geography_manage_view, name='geography_manage'),
    path('api/geo/provinces/', views.api_geo_provinces, name='api_geo_provinces'),
    path('api/geo/districts/', views.api_geo_districts, name='api_geo_districts'),
    path('api/geo/communes/', views.api_geo_communes, name='api_geo_communes'),
    path('api/geo/villages/', views.api_geo_villages, name='api_geo_villages'),
    path('api/geo/district/save/', views.api_geo_district_save, name='api_geo_district_save'),
    path('api/geo/commune/save/', views.api_geo_commune_save, name='api_geo_commune_save'),
    path('api/geo/village/save/', views.api_geo_village_save, name='api_geo_village_save'),
    path('api/geo/delete/', views.api_geo_item_delete, name='api_geo_item_delete'),

    # 🚗 Vehicle & Motorbike Inventory & Loan Management (ពាក្យសុំខ្ចីទ្រព្យប្រើប្រាស់ & កំណត់ហេតុប្រគល់-ទទួល)
    path('vehicles/', views.vehicle_list, name='vehicle_list'),
    path('vehicles/new/', views.vehicle_create, name='vehicle_create'),
    path('vehicles/<int:pk>/edit/', views.vehicle_edit, name='vehicle_edit'),
    path('vehicles/<int:pk>/delete/', views.vehicle_delete, name='vehicle_delete'),
    path('vehicles/export/excel/', views.vehicle_export_excel, name='vehicle_export_excel'),

    path('vehicle-requests/', views.vehicle_request_list, name='vehicle_request_list'),
    path('vehicle-requests/new/', views.vehicle_request_create, name='vehicle_request_create'),
    path('vehicle-requests/<int:pk>/', views.vehicle_request_detail, name='vehicle_request_detail'),
    path('vehicle-requests/<int:pk>/edit/', views.vehicle_request_edit, name='vehicle_request_edit'),
    path('vehicle-requests/<int:pk>/delete/', views.vehicle_request_delete, name='vehicle_request_delete'),
    path('vehicle-requests/<int:pk>/approve/', views.vehicle_request_approve, name='vehicle_request_approve'),
    path('vehicle-requests/<int:pk>/reject/', views.vehicle_request_reject, name='vehicle_request_reject'),
    path('vehicle-requests/<int:pk>/handover/', views.vehicle_request_handover, name='vehicle_request_handover'),
    path('vehicle-requests/<int:pk>/return/', views.vehicle_request_return, name='vehicle_request_return'),
    path('vehicle-requests/<int:pk>/print/', views.vehicle_request_print, name='vehicle_request_print'),
    path('vehicle-requests/<int:pk>/upload-photos/', views.vehicle_request_upload_photos, name='vehicle_request_upload_photos'),
    path('vehicle-requests/export/excel/', views.vehicle_request_export_excel, name='vehicle_request_export_excel'),
    path('api/vehicle-requests/officer-info/', views.api_get_officer_info, name='api_get_officer_info'),

    # 📋 Attendance Management Module (ម៉ូឌុលគ្រប់គ្រងវត្តមានមន្ត្រី និងមន្ត្រីជាប់កិច្ចសន្យា - Attendend A)
    path('attendance/', views.attendance_daily_entry, name='attendance_index'),
    path('attendance/daily/', views.attendance_daily_entry, name='attendance_daily_entry'),
    path('attendance/weekly/', views.attendance_weekly_sheet, name='attendance_weekly_sheet'),
    path('attendance/weekly/print/', views.attendance_weekly_print, name='attendance_weekly_print'),
    path('attendance/weekly/export/excel/', views.attendance_weekly_export_excel, name='attendance_weekly_export_excel'),
    path('attendance/monthly/', views.attendance_monthly_sheet, name='attendance_monthly_sheet'),
    path('attendance/monthly/print/', views.attendance_monthly_print, name='attendance_monthly_print'),
    path('attendance/monthly/export/excel/', views.attendance_monthly_export_excel, name='attendance_monthly_export_excel'),
    path('attendance/reports/', views.attendance_summary_report, name='attendance_summary_report'),
    path('attendance/annual-bulletin/', views.attendance_annual_bulletin, name='attendance_annual_bulletin'),
    path('attendance/annual-bulletin/print/', views.attendance_annual_bulletin_print, name='attendance_annual_bulletin_print'),
    path('attendance/annual-bulletin/export/excel/', views.attendance_annual_bulletin_export_excel, name='attendance_annual_bulletin_export_excel'),
    path('attendance/api/quick-toggle/', views.api_attendance_quick_toggle, name='api_attendance_quick_toggle'),

    # 👑 Leadership Attendance Module (វត្តមានថ្នាក់ដឹកនាំ ខណ្ឌ និងប្រធានការិយាល័យ - Attendend B)
    path('attendance/leadership/daily/', views.attendance_leadership_daily, name='attendance_leadership_daily'),
    path('attendance/leadership/weekly/', views.attendance_leadership_weekly, name='attendance_leadership_weekly'),
    path('attendance/leadership/weekly/print/', views.attendance_leadership_weekly_print, name='attendance_leadership_weekly_print'),
    path('attendance/leadership/weekly/export/excel/', views.attendance_leadership_weekly_export_excel, name='attendance_leadership_weekly_export_excel'),
    path('attendance/leadership/monthly/', views.attendance_leadership_monthly, name='attendance_leadership_monthly'),
    path('attendance/leadership/monthly/print/', views.attendance_leadership_monthly_print, name='attendance_leadership_monthly_print'),
    path('attendance/leadership/monthly/export/excel/', views.attendance_leadership_monthly_export_excel, name='attendance_leadership_monthly_export_excel'),
]

